apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: takwa99/mvn_image:latest
        ports:
        - containerPort: 8080   
        imagePullPolicy: Never 
        command: ["/bin/sh"]
        args: ["-c", "sleep 1000 && echo Sleep expired > /dev/termination-log"]
          


