pipeline {
  environment {
    DOCKERHUB_CREDENTIALS = credentials('DockerHub')
  }
  agent none
  stages {
    stage('Maven Install') {
      agent {
        docker {
          image 'maven:3.8.4'
        }
      }
      steps {
        sh 'mvn clean install'
      }
    }
    stage('Docker Build') {
      agent any
      steps {
        sh 'docker build -f Dockerfile -t mvn_image .'
      }
    }
    stage('Login') {
      agent any
      steps {
        sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
      }
    }

    stage('Push') {
      agent any
      steps {
        sh 'docker tag mvn_image takwa99/mvn_image'
        sh 'docker push takwa99/mvn_image:latest'
      }
    }
    stage('deploy to k8s') {
      agent any
      steps {
        withKubeConfig([credentialsId: 'kube']) {
          sh 'kubectl create -f https://raw.githubusercontent.com/tahritakwa/mvn_repo/master/my-app/deployment.yml'
        }
      }
    }
  }
}
