pipeline {
    agent none
   stages {     
    stage('Maven Install') {
      agent {         
       docker {          
         image 'maven:3.5.0'         
     }       
  }       
  steps dir("/var/lib/jenkins/workspace/mvn_build/my-app") {
       sh 'mvn clean install'
       }
     }
   }
 }
